name: health_hub

description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^5.2.1
  http: ^0.13.3
  youtube_player_flutter: ^8.0.0
  flutter_pdfview: ^1.3.4
  path_provider: ^2.0.9
  image_picker: ^0.8.4+8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
